base_url = "https://mkersten.net"
theme = "duckquill"
compile_sass = true
build_search_index = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml"]
title = "Home"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "monokai"
smart_punctuation = true
bottom_footnotes = true

[search]
index_format = "elasticlunr_json"

[extra]
emoji_favicon = "🐱"
accent_color = "#19160A"
accent_color_dark = "#FFD866"
default_theme = "dark"
source_url = "https://github.com/chirpcel"
styles = ["mods.css"]
show_copy_button = true

[extra.nav]
show_feed = true
show_theme_switcher = false
show_repo = true
links = [
    { name = "Projects", menu = [
		{ url = "@/projects/ddns6-worker.md", name = "ddns6-worker" },
		{ url = "@/projects/ssh-sign.md", name = "ssh-sign" }
	] },
    { url = "@/blog/_index.md", name = "Blog" }
]

[extra.footer]
show_copyright = true
show_powered_by = true
show_source = false
copyright = "© Marcel Kersten, 2024"
