name: Deploy Zola site to Cloudflare Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "cloudflare-pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
    steps:
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Zola
        run: |
          cd mkersten.net
          zola build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./mkersten.net/public --project-name=mkersten
